### PR TITLE
Fix the wide indent of the xml to fit on a screen

### PR DESCRIPTION
**Pull request by maxandersen**

### CODE REVIEW

**Comment by maxandersen** [comment]
just noticed I could not fit in the pom.xml on my 27" screen. seemed a bit too much so here is a fix for that ;)

**Comment by nickboldt** [comment]
You don't need to provide a PR for cleaning up whitespace. Merged.

**Comment by maxandersen** [comment]
since whitespace fixes would/could break ongoing PR's I didn't push it directly.

**Comment by nickboldt** [comment]
Ah, good point. Carry on, then. :)

**Pull request closed without merging**
