### PR TITLE
Add maven settings.xml file, fixes JBIDE-27663

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@sbouchet  Please take a look.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Review by sbouchet — APPROVED** [review]
LGTM.

**Comment by odockal** [comment]
@sbouchet @jeffmaury I do not have right to merge

**Pull request merged**
